apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: seti-pod
  labels:
    app: "BOINC_Client"
spec:
  template:
    metadata:
      labels:
        os: "Ubuntu_14.04"
        app: "BOINC_Client"
        project: "setiAtHome"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: "project-data"
        hostPath:
          path: "/var/lib/boinc"
      terminationGracePeriodSeconds: 30
      containers:
      - image: docker.io/wshoffner/kube-boinc:14.04
        name: seti-pod
        resources:
          requests:
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        volumeMounts:
        - mountPath: "/data"
          name: "project-data"
        args: ["-attach_project", "http://setiathome.berkeley.edu/", "8091539_832f5810bc78a10f68b0fc75896c4811", "--abort_jobs_on_exit"]